### PR TITLE
optimized search time and insertion time O(1)

### PR DESCRIPTION
**Pull request by Pydare**
- Added functionalities for PHP, C#, Swift, R & Scala programming language files

- Optimization of the algorithm for checking if a file has been signed (checking the 0-50th index, instead of the whole string)

- Optimization of insertion of signature in the file, using the deque data structure, that reduces time complexity from O(n) to O(1)

### CODE REVIEW

**Review by Harjacober — CHANGES_REQUESTED** [review]
Awesome work mate.

Just a few points to note

- I think `R` doesn't support multi-line comments. Kindly check this [link.](https://www.google.com/amp/s/intelligea.wordpress.com/2013/06/30/inline-and-block-comments-in-r/amp/)
- Using the queue is not an effective Optimization as it takes O(n) time to create the `deque` object from the `contents` array, which is basically the same runtime as inserting the `signature` at the start index (which was implemented before).
- Awesome idea for checking only the first 50 contents in the file, that's a great optimization as the runtime is now reduced to O(1). I would just advise you left strip extra trailing spaces and lines in the file before getting the first 50 contents to search from.

Kindly make necessary adjustments based on the feedback I gave above, so I can merge your pull request.

**Comment by haibeey** [comment]
> * Using the queue is not an effective Optimization as it takes O(n) time to create the `deque` object from the `contents` array, which is basically the same runtime as inserting the `signature` at the start index (which was implemented before).

The appending with deque is faster though. see [deque](https://docs.python.org/3.8/library/collections.html#collections.deque).

Quoted directly from the docs "Though list objects support similar operations, they are optimized for fast fixed-length operations and incur O(n) memory movement costs for pop(0) and insert(0, v) operations which change both the size and position of the underlying data representation." with deque ends operations are O(1)

**Comment by Harjacober** [comment]
Yes Abraham. The appending with deque is faster but what I'm trying to point out is that intializing the `deque` object with the `contents` array takes O(n) time.

**Comment by Pydare** [comment]
* Using the queue is not an effective Optimization as it takes O(n) time to create the `deque` object from the `contents` array, which is basically the same runtime as inserting the `signature` at the start index (which was implemented before).

Creating a deque object doesn't take O(n) time as it is the same thing as creating a list or an array. I strongly disagree with your point, except you could share a link that explains this

**Comment by Harjacober** [comment]
Hi Dare.
Initializing the deque object takes O(n) time, where n is the length of the array. The `deque` data structure is implemented internally with a Double-LinkedList, which means to create the `deque` object from an array, we have to iterate through all the elements in the array which takes O(n) time.
Initializing an empty `deque` will take constant time, but initializing it from an array will take O(n) time, there's no workaround.

**Pull request merged**
